// API TYPES
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const USER_DATA_REPORT = 'USER_DATA_REPORT';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA__FAILURE = 'USER_DATA__FAILURE';

export const POST_OWNER_DATA = 'POST_OWNER_DATA';
export const POST_OWNER_DATA_SUCCESS = 'POST_OWNER_DATA_SUCCESS';
export const POST_OWNER_DATA_FAILURE = 'POST_OWNER_DATA_FAILURE';
